name: flock
description:
  |
  Coordinate Flutter widgets' states with event sourcing.
    What if Redux store contains no reducers, no state but only actions?
version: 0.7.1
author: Bo Bao <bob432091@gmail.com>
homepage: https://github.com/pinyin/flock

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  collection: ^1.14.11
  uuid: ^2.0.2

dev_dependencies:
  matcher: ^0.12.3
  test: ^1.0.0

